### Site info:
title: 代盼华的博客
tagline: 面朝大海，春暖花开
author: Lijia Yu
email: daipanhua@gmail.com
description: "面朝大海，春暖花开" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "代盼华, android"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daipanhua.github.io/" # the base hostname & protocol for your site
locale: zh_cn

### Personal info and site tools info:
github_username:  daipanhua
disqus_shortname: daipanhua
favicon:     "/images/favicon.ico"
aboutme: 我是代盼华，这是我的个人博客. # these are shown on aboutme-sidebar.
aboutme_photo: https://avatars.githubusercontent.com/daipanhua # your photo.

analytics :
    provider : custom
### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      # Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Denny
      href: http://daipanhua.github.io/
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
